version: "3.9"

services:
    upload-service:
      image: neel0086/upload-service:latest
      container_name: upload-service
      networks:
        - netflix-net
      depends_on:
        - eureka-server
        - kafka
        - mongo
        - minio
      ports:
        - "8080:8080"
      environment:
        - spring.application.name=UPLOAD-SERVICE
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
        - server.port=8080

        # Mongo
        - MONGO_URI=mongodb://mongo:27017/upload_db

        # MinIO (AWS-SDK endpointOverride)
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_ACCESS_KEY=minioadmin
        - MINIO_SECRET_KEY=minioadmin
        - MINIO_UPLOAD_BUCKET=video-uploads

        # Kafka
        - KAFKA_BOOTSTRAP=kafka:9092
        - KAFKA_UPLOAD_TOPIC=upload.events

