version: "3.9"

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:7.3.0
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
      networks:
        - netflix-net

    kafka:
      image: confluentinc/cp-kafka:7.3.0
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      networks:
        - netflix-net

    upload-service:
      image: neel0086/upload-service:latest
      container_name: upload-service
      networks:
        - netflix-net
      depends_on:
        - eureka-server
        - kafka
        - mongo
        - minio
      ports:
        - "8080:8080"
      environment:
        - spring.application.name=UPLOAD-SERVICE
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
        - server.port=8080

        # Mongo
        - MONGO_URI=mongodb://mongo:27017/upload_db

        # MinIO (AWS-SDK endpointOverride)
        - MINIO_ENDPOINT=http://minio:9000
        - MINIO_ACCESS_KEY=minioadmin
        - MINIO_SECRET_KEY=minioadmin
        - MINIO_UPLOAD_BUCKET=video-uploads

        # Kafka
        - KAFKA_BOOTSTRAP=kafka:9092
        - KAFKA_UPLOAD_TOPIC=upload.events

