server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongo:27017/upload_db}

# MinIO settings
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket:
    uploads: ${MINIO_UPLOAD_BUCKET:video-uploads}


# Kafka
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
  topic:
    upload: ${KAFKA_UPLOAD_TOPIC:upload.events}
